# Generated by Django 4.2.27 on 2026-01-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='_type',
            field=models.CharField(choices=[('Footwear', 'Footwear')], max_length=10),
        ),
    ]
