# Generated by Django 4.2.27 on 2026-01-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='_type',
            field=models.CharField(blank=True, choices=[('Boot', 'Boot')], max_length=10),
        ),
    ]
