# Generated by Django 4.2.27 on 2026-01-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_bootlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootlog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boot_logs/'),
        ),
    ]
