# Generated by Django 4.2.27 on 2026-01-17 00:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
