# Generated by Django 4.2.27 on 2026-01-17 15:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_alter_item__type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemLog',
            new_name='Photo',
        ),
    ]
