# Generated by Django 4.2.27 on 2026-01-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item__type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='_type',
            field=models.CharField(choices=[('Boot', 'Boot')], max_length=10),
        ),
    ]
