# Generated by Django 4.2.27 on 2026-01-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
