# Generated by Django 4.2.27 on 2026-01-17 15:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_rename_itemlog_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PhotoLog',
        ),
    ]
