# Generated by Django 4.2.27 on 2026-01-14 10:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_bootlog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootlog',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
