# Generated by Django 4.2.27 on 2026-01-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_photo_options_photo_wore_on_alter_photo_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='model',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='item',
            new_name='item_id',
        ),
    ]
