# Generated by Django 4.2.27 on 2026-01-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_rename_model_item_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='shared_feed',
            field=models.BooleanField(default=True),
        ),
    ]
