# Generated by Django 4.2.27 on 2026-01-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_photo_shared_feed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='item_id',
            new_name='item',
        ),
    ]
